name: Build Carti Mod
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Use '21' if you are targeting Minecraft 1.20.5 or newer
          distribution: 'temurin'

      - name: Make Gradle Executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Mod Jar
        uses: actions/upload-artifact@v4
        with:
          name: Pissy-Pamper-Mod
          path: build/libs/*.jar
